/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactIdRouteImport } from './routes/artifact.$id'

const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactIdRoute = ArtifactIdRouteImport.update({
  id: '/artifact/$id',
  path: '/artifact/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/artifact/$id': typeof ArtifactIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/artifact/$id': typeof ArtifactIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/artifact/$id': typeof ArtifactIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collections' | '/artifact/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collections' | '/artifact/$id'
  id: '__root__' | '/' | '/collections' | '/artifact/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  ArtifactIdRoute: typeof ArtifactIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifact/$id': {
      id: '/artifact/$id'
      path: '/artifact/$id'
      fullPath: '/artifact/$id'
      preLoaderRoute: typeof ArtifactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  ArtifactIdRoute: ArtifactIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
